version: "2.1"

services:
  namenode:
    build: ./namenode
    container_name: namenode
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - "9870:9870"
    networks:
      - bigdata-net

  resourcemanager:
    build: ./resourcemanager
    container_name: resourcemanager
    restart: on-failure
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
      - datanode4
    env_file:
      - ./hadoop.env
    ports:
      - "8089:8088"
    networks:
      - bigdata-net

  historyserver:
    build: ./historyserver
    container_name: historyserver
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
      - datanode4
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    ports:
      - "8188:8188"
    networks:
      - bigdata-net

  nodemanager1:
    build: ./nodemanager
    container_name: nodemanager1
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
      - datanode4
    env_file:
      - ./hadoop.env
    ports:
      - "8042:8042"
    networks:
      - bigdata-net

  datanode1:
    build: ./datanode
    container_name: datanode1
    restart: always
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - bigdata-net

  datanode2:
    build: ./datanode
    container_name: datanode2
    restart: always
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - bigdata-net

  datanode3:
    build: ./datanode
    container_name: datanode3
    restart: always
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - bigdata-net

  datanode4:
    build: ./datanode
    container_name: datanode4
    restart: always
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode4:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks:
      - bigdata-net

  spark-master:
    image: bde2020/spark-master:3.1.2-hadoop3.2
    container_name: spark-master
    hostname: spark-master       
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - "8080:8080"
      - "7077:7077"
    env_file:
      - ./hadoop.env
    networks:
      - bigdata-net

  spark-worker:
    image: bde2020/spark-worker:3.1.2-hadoop3.2
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=2G
    ports:
      - "8081:8081"
    env_file:
      - ./hadoop.env
    networks:
      - bigdata-net

  pyspark:
    image: jupyter/pyspark-notebook:spark-3.1.2
    container_name: pyspark-notebook
    depends_on:
      - spark-master
      - spark-worker
    ports:
      - "8888:8888"
    volumes:
      - ./notebook/:/home/jovyan/work/
    environment:
      - PYSPARK_SUBMIT_ARGS=--master spark://spark-master:7077 pyspark-shell
    networks:
      - bigdata-net


networks:
  bigdata-net:
    driver: bridge

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
  hadoop_datanode4:
  hadoop_historyserver:
